 * Serving Flask app 'task_tracker'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 894-435-962
Traceback (most recent call last):
  File "/Users/gabrielortiz/PycharmProjects/TaskTracker/task_tracker.py", line 82, in <module>
    app.run(debug=True)
    ~~~~~~~^^^^^^^^^^^^
  File "/Users/gabrielortiz/PycharmProjects/TaskTracker/.venv/lib/python3.13/site-packages/flask/app.py", line 662, in run
    run_simple(t.cast(str, host), port, self, **options)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gabrielortiz/PycharmProjects/TaskTracker/.venv/lib/python3.13/site-packages/werkzeug/serving.py", line 1115, in run_simple
    run_with_reloader(
    ~~~~~~~~~~~~~~~~~^
        srv.serve_forever,
        ^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        reloader_type=reloader_type,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/gabrielortiz/PycharmProjects/TaskTracker/.venv/lib/python3.13/site-packages/werkzeug/_reloader.py", line 459, in run_with_reloader
    ensure_echo_on()
    ~~~~~~~~~~~~~~^^
  File "/Users/gabrielortiz/PycharmProjects/TaskTracker/.venv/lib/python3.13/site-packages/werkzeug/_reloader.py", line 439, in ensure_echo_on
    termios.tcsetattr(sys.stdin, termios.TCSANOW, attributes)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
termios.error: (4, 'Interrupted system call')
Fatal Python error: init_sys_streams: can't initialize sys standard streams
Python runtime state: core initialized
OSError: [Errno 9] Bad file descriptor

Current thread 0x00000001f1746500 (most recent call first):
  <no Python frame>
